### PR TITLE
process db2feather added

### PR DESCRIPTION
**Pull request by GhadaNOUAIRIA**
Outputs error while writing taxa

### CODE REVIEW

**Comment by erikrikarddaniel** [comment]
I can replicate this. I need to see what's wrong with the script.
(BTW, the commit message should say what you did, not what's not working. You can put that message into an issue.)

**Comment by erikrikarddaniel** [comment]
Another BTW, it's better to open an issue than a pull request when something is not working. One doesn't want to merge code that's not working.

**Comment by GhadaNOUAIRIA** [comment]
I pushed recent changes with main.nf complete and working.
I can't ask for a new pull request since you did not merge the previous one.
Please pull and check if the script works for you

**Comment by erikrikarddaniel** [comment]
Right, I merged now.

**Pull request merged**
